server:
  address: ":8070"

target:
  - http://localhost:8080

cache:
  engine: fs
  location: "./tmp/cache"
  options:
    log-miss: true
    log-hit: false
    ignore-headers: false
    log-request-headers: false


